### ISSUE TITLE
Using Safety Settings

### ISSUE THREAD

**Issue by DickyMacias** [gbaptista/gemini-ai#15]
Hi, @gbaptista.

Is it possible to use Safety Settings in the gem? I'm attempting to analyze certain content, but the process concludes due to a high HARM_CATEGORY_DANGEROUS_CONTENT reason. According to the Gemini API documentation, Safety Settings can be applied in this context, but I've been unsuccessful in make it work with the gem. Specifically, I'm using gemini-pro-vision to scan an image of a pesticide.

safetySettings: {
    HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
}

I will appreciate your help with this. Thanks.

**Comment by gbaptista** [comment]
Hey, thanks for opening the issue. Have you tried this?
```ruby
client.stream_generate_content(
  {
    contents: { role: 'user', parts: { text: 'hi!' } },
    safetySettings: [
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_NONE'
      },
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_NONE'
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_NONE'
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE'
      }
    ]
  }
)
```

**Comment by DickyMacias** [comment]
Thanks, @gbaptista. I am going to check it and let you know how it works.

**Comment by gbaptista** [comment]
I added a [Safety Settings](https://github.com/gbaptista/gemini-ai#safety-settings) section in the README, and, FYI, Google started to block the usage of `BLOCK_NONE` unless:

> _User has requested a restricted HarmBlockThreshold setting BLOCK_NONE. You can get access either (a) through an allowlist via your Google account team, or (b) by switching your account type to monthly invoiced billing via this instruction: https://cloud.google.com/billing/docs/how-to/invoiced-billing_
